#ifndef GUARD_DY_META_DESCRIPTOR_SCRIPTDESCRIPTOR_H
#define GUARD_DY_META_DESCRIPTOR_SCRIPTDESCRIPTOR_H
///
/// MIT License
/// Copyright (c) 2018 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <string>

namespace dy
{

///
/// @struct PDyMetaScriptInformation
/// @brief
///
struct PDyMetaScriptInformation final
{
  std::string mName             = MDY_INITILAIZE_EMPTYSTR;
  std::string mScriptPath       = MDY_INITILAIZE_EMPTYSTR;
  std::string mScriptCode       = MDY_INITILAIZE_EMPTYSTR;

  bool mIsUsingScriptPath       = false;
  bool mIsUsingScriptInnateCode = false;
};

} /// ::dy namespace

#endif /// GUARD_DY_META_DESCRIPTOR_SCRIPTDESCRIPTOR_H