#ifndef GUARD_DY_BUITLIN_ATTACHMENT_SCENEINTEGRATION_H
#define GUARD_DY_BUITLIN_ATTACHMENT_SCENEINTEGRATION_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Builtin/Abstract/ADyGLAttachmentResource.h>
#include <Dy/Core/Reflection/RDyBuiltinResources.h>

namespace dy
{

///
/// @class FDyBtAttOutput
/// @brief scene integration color attachment information attachment
///
class FDyBtAttOutput final : public ADyGLAttachmentResource
{
  MDY_REGISTER_RESOURCE_ATTACHMENT(FDyBtAttOutput, "dyBtAtScrFin_Output")
};

} /// ::dy namespace

#endif /// GUARD_DY_BUITLIN_ATTACHMENT_SCENEINTEGRATION_H