#ifndef GUARD_DY_BUITLIN_MESH_DEBUG_FDyBtMsDebugSphere_H
#define GUARD_DY_BUITLIN_MESH_DEBUG_FDyBtMsDebugSphere_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Builtin/Abstract/AMeshResource.h>

namespace dy::builtin
{

///
/// @class FDyBtMsDebugSphere
/// @brief mesh sphere for debugging collision shape. (not AABB)
///
class FDyBtMsDebugSphere final : public AMeshResource
{
  MDY_REGISTER_RESOURCE_MESH(FDyBtMsDebugSphere, "dyBtMsDebugSphere");
};

} /// ::dy::builtin namespace

#endif /// GUARD_DY_BUITLIN_MESH_DEBUG_FDyBtMsDebugSphere_H