///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Math/Common/TGlobalTypes.h>
#include <Math/Common/XGlobalMacroes.h>

namespace dy::math
{

MATH_UNUSED_VAR = kMaxValueOf<TChr8>;
MATH_UNUSED_VAR = kMaxValueOf<TChr16>;
MATH_UNUSED_VAR = kMaxValueOf<TChr32>;
MATH_UNUSED_VAR = kMaxValueOf<TU8>;
MATH_UNUSED_VAR = kMaxValueOf<TU16>;
MATH_UNUSED_VAR = kMaxValueOf<TU32>;
MATH_UNUSED_VAR = kMaxValueOf<TU64>;
MATH_UNUSED_VAR = kMaxValueOf<TI8>;
MATH_UNUSED_VAR = kMaxValueOf<TI16>;
MATH_UNUSED_VAR = kMaxValueOf<TI32>;
MATH_UNUSED_VAR = kMaxValueOf<TI64>;
MATH_UNUSED_VAR = kMaxValueOf<TF32>;
MATH_UNUSED_VAR = kMaxValueOf<TF64>;
MATH_UNUSED_VAR = kMaxValueOf<TIndex>;

MATH_UNUSED_VAR = kMinValueOf<TChr8>;
MATH_UNUSED_VAR = kMinValueOf<TChr16>;
MATH_UNUSED_VAR = kMinValueOf<TChr32>;
MATH_UNUSED_VAR = kMinValueOf<TU8>;
MATH_UNUSED_VAR = kMinValueOf<TU16>;
MATH_UNUSED_VAR = kMinValueOf<TU32>;
MATH_UNUSED_VAR = kMinValueOf<TU64>;
MATH_UNUSED_VAR = kMinValueOf<TI8>;
MATH_UNUSED_VAR = kMinValueOf<TI16>;
MATH_UNUSED_VAR = kMinValueOf<TI32>;
MATH_UNUSED_VAR = kMinValueOf<TI64>;
MATH_UNUSED_VAR = kMinValueOf<TF32>;
MATH_UNUSED_VAR = kMinValueOf<TF64>;
MATH_UNUSED_VAR = kMinValueOf<TIndex>;

} /// ::dy::math namespace