#ifndef GUARD_DY_BUILTIN_HELPER_BUITLININFORMATIONDELIVER_H
#define GUARD_DY_BUILTIN_HELPER_BUITLININFORMATIONDELIVER_H
///
/// MIT License
/// Copyright (c) 2018 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

namespace dy
{

///
/// @struct FDyBuiltinInformationDeliver
/// @brief
///
struct FDyBuiltinInformationDeliver final
{
public:
  ///
  /// @brief
  /// @param  metaString
  /// @return
  ///
  static MDY_NODISCARD EDySuccess ForwardWidgetMetaInformation(_MIN_ const std::string_view& metaString);

};

} /// ::dy namespace

#endif /// GUARD_DY_BUILTIN_HELPER_BUITLININFORMATIONDELIVER_H