#ifndef GUARD_DY_COMPONENT_INTERNAL_CAMERA_DUBOCAMERABLOCK_H
#define GUARD_DY_COMPONENT_INTERNAL_CAMERA_DUBOCAMERABLOCK_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Helper/Type/DMatrix4x4.h>

namespace dy
{
  
/// @brief specifier name for ubo "CameraBlock"
MDY_SET_IMMUTABLE_STRING(sUboCameraBlock, "dyBtUboCameraBlock");

/// @struct DUboCameraBlock
/// @brief  This structure must be aligned by 16 bytes.
struct alignas(16) DUboCameraBlock final
{
  DMat4 mProjMatrix = {};
  DMat4 mViewMatrix = {};
};

} /// ::dy namespace

#endif /// GUARD_DY_COMPONENT_INTERNAL_CAMERA_DUBOCAMERABLOCK_H