#ifndef GURAD_DY_BUILTIN_ATTACHMENT_BASICSHADOW_BASICSHADOW_H
#define GURAD_DY_BUILTIN_ATTACHMENT_BASICSHADOW_BASICSHADOW_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Builtin/Abstract/ADyGLAttachmentResource.h>
#include <Dy/Core/Reflection/RDyBuiltinResources.h>

namespace dy
{

///
/// @class FDyBtAttachmentBasicShadow
/// @brief basic shadow information attachment
///
class FDyBtAttachmentBasicShadow final : public ADyGLAttachmentResource
{
  MDY_REGISTER_RESOURCE_ATTACHMENT(FDyBtAttachmentBasicShadow, "dyBtAtDirBscShadow")
};

} /// ::dy namespace

#endif /// GURAD_DY_BUILTIN_ATTACHMENT_BASICSHADOW_BASICSHADOW_H