#ifndef GUARD_DY_CORE_INTERFACE_UPDATABLE_H
#define GUARD_DY_CORE_INTERFACE_UPDATABLE_H
///
/// MIT License
/// Copyright (c) 2018 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

namespace dy
{

///
/// @class IDyUpdatable
/// @brief The inteface capable of updating derived class routine.
///
class MDY_NO_VTABLE IDyUpdatable
{
public:
  virtual ~IDyUpdatable() = default;
  virtual void Update(float dt) = 0;
};

} /// ::dy namespace

#endif /// GUARD_DY_CORE_INTERFACE_UPDATABLE_H