#ifndef GUARD_DY_INCLUDE_ENTRY_H
#define GUARD_DY_INCLUDE_ENTRY_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <filesystem>
#include <regex>

#include <Dy/Core/DyEngine.h>
#include <Dy/Helper/Library/HelperRegex.h>
#include <Dy/Helper/Library/HelperJson.h>
#include <Dy/Management/WindowManager.h>
#include <Dy/Management/SettingManager.h>

#endif /// GUARD_DY_INCLUDE_ENTRY_H