#ifndef GUARD_DY_HELPER_TYPE_DYSTRING_H
#define GUARD_DY_HELPER_TYPE_DYSTRING_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Helper/Library/HelperString.h>
#include <StringUtil/DU16String.h>

namespace dy
{

using DString = DU16String;

/// @macro  MIMMSTR
/// @brief  Just
/// @mparam __MACString__
#define MIMMSTR(__MACString__) ::dy::DString{__MACString__}

} /// ::dy namespace

#endif /// GUARD_DY_HELPER_TYPE_DYSTRING_H