#ifndef GUARD_DY_ELEMENT_TYPE_TIMER_EDYTIMERSTATUS_H
#define GUARD_DY_ELEMENT_TYPE_TIMER_EDYTIMERSTATUS_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

namespace dy
{

/// @enum   EDyTimerStatus
/// @brief  TimerStatus of general timer instance.
enum class EDyTimerStatus : unsigned char
{
  Play,   //
  Paused, // 
  Aborted // Status only will be changed to this when Script is moved to GClist.
};

} /// ::dy namespace

#endif /// GUARD_DY_ELEMENT_TYPE_TIMER_EDYTIMERSTATUS_H
