#ifndef GUARD_DY_CORE_RENDERING_WRAPPER_PDYGLSHADERFRAGMENTDESCRIPTOR_H
#define GUARD_DY_CORE_RENDERING_WRAPPER_PDYGLSHADERFRAGMENTDESCRIPTOR_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Meta/Type/EDyResourceTypes.h>

namespace dy
{

///
/// @struct PDyGLShaderFragmentDescriptor
/// @brief Descriptor instance for creating shader fragment context of opengl.
///
struct PDyGLShaderFragmentDescriptor final
{
  EDyShaderFragmentType mType       = EDyShaderFragmentType::NoneError;
  const char*           mPtrBuffer  = MDY_INITIALIZE_NULL;
};

} /// ::dy namespace

#endif /// GUARD_DY_CORE_RENDERING_WRAPPER_PDYGLSHADERFRAGMENTDESCRIPTOR_H