#ifndef GUARD_DY_BUITLIN_TEXTURE_SSAONoiseMap_H
#define GUARD_DY_BUITLIN_TEXTURE_SSAONoiseMap_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

#include <Dy/Builtin/Abstract/ADyTextureResource.h>

namespace dy::builtin
{

/// @class FDyBtTexSSAONoiseMap
/// @brief Noise texture for SSAO effect.
class FDyBtTexSSAONoiseMap final : public ADyTextureResource
{
  MDY_REGISTER_RESOURCE_TEXTURE(FDyBtTexSSAONoiseMap, "dyBtTexSSAONoiseMap")
};

} /// ::dy::builtin namespace

#endif /// GUARD_DY_BUITLIN_TEXTURE_SSAONoiseMap_H