#ifndef GUARD_DY_MANAGEMENT_TYPE_RENDER_DDyPixelInfo_H
#define GUARD_DY_MANAGEMENT_TYPE_RENDER_DDyPixelInfo_H
///
/// MIT License
/// Copyright (c) 2018-2019 Jongmin Yun
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

namespace dy
{

/// @struct DDyPixelInfo
/// @brief Pixel information of object picking.
struct DDyPixelInfo final
{
  float ObjectID = 0.0f;
  float DrawID = 0.0f;
  float PrimID = 0.0f;
};

}

#endif /// GUARD_DY_MANAGEMENT_TYPE_RENDER_DDyPixelInfo_H
